# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "cis_courses", :force => true do |t|
    t.column "cis_subject_id", :integer, :default => 0, :null => false
    t.column "number", :integer, :limit => 3, :default => 0, :null => false
    t.column "title", :string, :limit => 30, :default => "", :null => false
  end

  create_table "cis_courses_course_bins", :id => false, :force => true do |t|
    t.column "cis_course_id", :integer, :default => 0, :null => false
    t.column "course_bin_id", :integer, :default => 0, :null => false
  end

  create_table "cis_courses_semesters", :id => false, :force => true do |t|
    t.column "cis_course_id", :integer, :default => 0, :null => false
    t.column "semester_id", :integer, :default => 0, :null => false
  end

# Could not dump table "cis_sections" because of following StandardError
#   Unknown type 'set('M','T','W','R','F','S')' for column 'days'

# Could not dump table "cis_sections_backup" because of following StandardError
#   Unknown type 'set('M','T','W','R','F','S')' for column 'days'

  create_table "cis_sections_course_plans", :id => false, :force => true do |t|
    t.column "cis_section_id", :integer, :default => 0, :null => false
    t.column "course_plan_id", :integer, :default => 0, :null => false
  end

# Could not dump table "cis_semesters" because of following StandardError
#   Unknown type 'year(4)' for column 'year'

  create_table "cis_subjects", :force => true do |t|
    t.column "code", :string, :limit => 6, :default => "", :null => false
  end

  add_index "cis_subjects", ["code"], :name => "code", :unique => true

  create_table "colleges", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "code", :string, :limit => 2, :default => "", :null => false
  end

  create_table "course_bins", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
  end

  create_table "course_plans", :force => true do |t|
    t.column "semester_id", :integer, :default => 0, :null => false
  end

  create_table "friend_lists", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
  end

  create_table "friend_lists_users", :id => false, :force => true do |t|
    t.column "friend_list_id", :integer, :default => 0, :null => false
    t.column "user_id", :integer, :default => 0, :null => false
  end

  create_table "majors", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "name", :string, :default => "", :null => false
  end

  add_index "majors", ["name"], :name => "name", :unique => true

# Could not dump table "semesters" because of following StandardError
#   Unknown type 'year(4)' for column 'year'

# Could not dump table "users" because of following StandardError
#   Unknown type 'year(4)' for column 'start_year'

end
